import React, { useEffect, useState } from "react";
import {
  Text,
  TouchableOpacity,
  View,
  FlatList,
  ScrollView,
} from "react-native";
import { tw } from "../../tailwind";
import Container from "../components/Container";

import { NavigationProps } from "../RouteParamList";

const hundredPack = [
  [
    "Den som er med på leken må smake steken, kast boksen til den som oftest går over streken",
    "Nå har vi funnet kveldens grensekrysser, den neste som får boksen er rommets beste kysser. (Må kysse personen)",
    "Nå er drikkeleken godt i gang, hvem er rommets blikkfang?",
    "Du utmerker deg godt i mengden, hvem skal ha creds for lengden?",
    "Du har kanskje stor pikk, men hvem i rommet  har alltid åpen butikk?",
    "Om du har åpent i dag eller ei, kast til den som aldri hadde fått deg.",
    "Ohh den var hard å få, men hvem i rommet har vanskeligst for å få stå? ",
    "Dette kan vi gjøre noe med, hiv boksen til den du vil lapdance se. (Får lapdance)",
    "Det var litt av en dans må jeg si, hvem sin personlighet er 10/10?",
    "Du må jammen være snill, men hvem av oss er mest vill?",
    "Du liker å slå deg løs, men hvem er størst tindertøs?",
    "Nye mennesker er du ikke redd for å treffe, hvem i rommet liker å stå i doggystyle og bjeffe?",
    "Voff voff, du er spenstig i sengen, hvem her velger ligg over gjengen?",
    "Ai håper i hvert fall det var digg, men hvem her trenger nødig et ligg? ",
    "Du trenger å få deg fitte eller kuk, hvem her har høyest pengeforbruk?",
    "På byen bruker du flere tusen, hvem her er mest gnien på musen?",
    "Er du kresen eller er du bare en luremus, kast til den som oftest får bakrus.",
    "I kveld får du ta det rolig på drikken, hvem her er oftest på helseklinikken?",
    "Husk at det går an å bruke kondom, hvem her har et syndrom?",
    "Det går bra, du er god som du er, kast til en som må bytte klær. (Kasteren velger byttepartner også)",
    "Nå var dere fine, kast til den som med den til høyre for seg må kline. ",
    "Nå tok stemningen seg opp, hvem sørger alltid for at den er på topp?",
    "Du må være gøy på fest, men hvem er festens verste gjest?",
    "Skjerp deg, ikke vær så teit, hvem i rommet synes du er heit?",
    "Ohh ser jeg en gnist? Hvem er rommets største egoist? ",
    "Det er viktig å også tenke på andre, hvem i rommet kan du som feigest klandre? (Motbevis det, klin med den du har et øye til i kveld? ",
    "Der fortjener du heder og ære, hvem her klarer ikke å singel være?",
    "Den holdningen må ta slutt, hvem her kommer på under ett minutt?",
    "Viagra er kanskje tingen, hvem tar sjansen på å hopper av i svingen?",
    "Pass på så du ikke går på en smell, hvem her blir fullest i kveld?",
    "Ikke gidd å bli for full, hvem her er latest under knull?",
    "Innsats i senga har du ikke, den som har en fetisj må drikke (si hvilken)",
    "Det å drikke går vi aldri lei, hvem her tar ikke nei for et nei?",
    "Dette er en dårlig egenskap, hvem her har best musikksmak?",
    "Det var litt av et kompliment, neste må vise sitt beste dansemove til en sang. ",
    "De movsa var ikke dum, hvem her får finest avkom?",
    "Vi gleder oss til å se dine små håpefulle, hvem her har lavest standard når de skal knulle? ",
    "Du får kanskje pule i fleng, men hvem her puler flest i samme gjeng?",
    "Kom deg ut av gjengen, hvem lager de sykeste lydene i sengen?",
    "Håper ikke det var lytt da du vridde deg i spasme, hvem her har oftest orgasme?",
    "Får håpe du får deg noe i kveld, hvem her er høyest på seg selv?",
    "Du lever kanskje i din egen sone, hvem her blir dårligst mann eller kone?",
    "Ai uheldige den som ender opp med deg, gi boksen til den som alltid blir lei seg.",
    "Ikke ta alt i verste mening, hvem her gjør det best på trening?",
    "Du er kanskje størst, men hvem i rommet tror du slår seg til ro først?",
    "Vent litt med å slå deg til ro, gi boksen til den som er mest utro.",
    "Fysj a meg tror ikke de var blid, hvem holder på med flest på samme tid? ",
    "Håper ikke de vet om hverandre, kast boksen til den som i fylla lar seg forandre. ",
    "Fylla har skylda sier de alle, men hvem her kan vi lykkeligst kalle?",
    "Tilsynelatende har du det bra, hvem i rommet lar skinnet bedra?",
    "Du skjuler nok meget, hvem her er flinkest til å ta det første steget?",
    "Du fikser deg nok som mest, kast til den som alltid har fest.",
    "Kåken er alltid fullstappa, hvem her klarer seg ikke uten mamma og pappa?",
    "Du har kanskje vanskelig for å slippe tak, hvem kunne du aldri tatt med i familieselskap?",
    "Vi dømmer ingen, hvem får først ring på fingeren? ",
    "De fleste giftemål går uansett rett vest, hvem her spanter mest? ",
    "Har du overgått kredittgrensen? Hvem puler oftest med mensen?",
    "Det høres ut som du er spontan, hvem har mest hår på sitt kjønnsorgan?",
    "Håper vi alle begynner å bli drita, hvem er oftest på sprita?",
    "Du er nok en kjenning på polet, hvem her gir faen i skole?",
    "Skole er kanskje ikke din sterke side, hvem har høyest sannsynlighet for å lykkes i livet?",
    "Det blir spennende å se hva livet bringer, hvem er det som oftest fylleringer?",
    "Du fylleringer kanskje mest, men hvem sittet oftest på  på fest?",
    "La telefonen ligge i kveld, kast til den som har høyest gjeld",
    "Pass på så det ikke går helt over styr, den neste som får boksen er den som oftest spyr. ",
    "Klarer du ikke å holde nede på drikken? Kast til den som skal si den beste sjekkereplikken.",
    "Nå ble vi passe ubekvem, hvem her kunne du tatt med deg hjem?",
    "Er det gjensidig, blir det knull? Hvem her puler flest 00? ",
    "Jo nærmere null, jo trangere hull, kast boksen til den som er minst full.(Chug)",
    "Du må drikke for du er for nykter, hvem i rommet sprer flest rykter? ",
    "Ai du er rommets sladrehank, kast boksen til den som får mest bank. ",
    "Håper at du neste gang vinner, hvem her er det som alltid på byen forsvinner?",
    "Hadde du det travelt da du forsvant? Hvem er festens største kverulant?",
    "Håper din tid som kverulant er omme, neste skal gi et kompliment til alle i rommet. ",
    "Det var hyggelig, når var du grei, kast til den som må ta en bodyshot av den til venstre for seg. ",
    "Håper ikke den går rett til hodet og lager kluss, hvem i rommet trenger en suss? (Den som kaster boksen kysser mottager) ",
    "Håper sussen var god selv under tvang, hvem her har høyest temperament? ",
    "I kveld får du være stille, hvem her kjøper oftest angrepille? ",
    "Den var kanskje litt frekk, hvem synes du har finest antrekk?",
    "Håper alle har kost seg til nå, den neste som får boksen en drikkepartner skal få! (Kaster velger en drikkepartner)",
    "På denne festen er det ingen som depper, hvem har finest sugelepper? ",
    "Der er det ingen tvil, kast til den som har finest smil",
    "Festens fineste smil er kåret, kast til den som er singel ut året?",
    "Du er i hvertfall singel og fri, kast til den som er flinkest til å ri",
    "JIhaa du må være litt av en rytter, hvem her drar flest gutter?",
    "Du får nok gutter så det suser, hvem her er størst hjerteknuser?",
    "I å knuse hjerter er du drøyest, hvem her snakker alltid høyest?",
    "Åherregud som du tyter, hvem er festens verste skryter? ",
    "Det er ikke kult å skryte i øst og vest, hvem her inkluderer mest?",
    "Det er du bror, kast boksen til den som har høyest kjendisfaktor",
    "Kjendiser er kule og pene, hvem i rommet går aldri på do alene?",
    "Er du ensom eller har du mye å fortelle? Hvem i rommet kunne vært et engangstilfelle?",
    "Håper ikke den setter varige men, hvem her er alltid for sen?",
    "Man kommer ikke for sent til fest, kast boksen til den som alltid drikker mest",
    "Drikkemesteren det er deg, hvem her har mest drama rundt seg?",
    "Det blir ofte drama rundt sex, hvem ligger venners eks?",
    "Det kan fort smelle, hvem her får seg finest ektefelle?",
    "Du ender kanskje opp med den fineste mannen eller dama, men hvem her får seg en sugarmama?  ",
    "Sugarmama kan være digg, men nå er det siste sjanse til å få deg ligg (kast til den du kunne tenkt deg å ligge med)",
    "Heia heia, det å drikke går vi aldri lei av! FELLESSKÅL 100 spørsmål",
  ],
  [
    "Alle som er i et forhold, drikk",
    "Hvem kaster opp i kveld?",
    "Hvem har på den fineste outfitten?",
    "Jeg har aldri fått betalt eller betalt for noe «seksuelt»",
    "Hvem tror du kan havne på legevakta som følge av fylla?",
    "Hvem kan pule for rulleplass?",
    "Hvem er den fineste av det motsatte kjønn?",
    "Hvem er mest tøffel?",
    "Pek på den som får seg noe i kveld",
    "ALLE DRIKKER 1 SLURK",
    "Jeg har aldri sovnet under sex",
    "Hvem bruker mest penger på klær?",
    "Hvem ender opp som pornostjerne/ stripper?",
    "Hvem tror du kunne hatt ett ons i natt?",
    "Jeg har aldri sett noen i dette rommet naken",
    "Hvem tror de kan danse, men kan  egentlig ikke?",
    "Hvem er d på tide at skal få fjerna spindelvevet mellom beina?",
    "Hvem husker ikke i morgen?",
    "Pek på den mest uskyldige",
    "ALLE DRIKKER 2 SLURKER",
    "Jeg har aldri vært bundet i senga",
    "Hvem kunne gifta seg i fylla i Vegas?",
    "Hvem kunne gifta seg for penger?",
    "Hvem skal ta 10 slurker/3shots med deg?",
    "Jeg har aldri spilt strippepoker",
    "Hvem er villest i senga?",
    "Hvem snuser mest?",
    "Hvem er alltid barbert og klar for alt?",
    "Pek på den som tror den er smartest, men som ikke er det",
    "ALLE DRIKKER 3 SLURKER",
    "Jeg har aldri ligget med noen i dette rommet",
    "Hvem havner i fengsel?",
    "Hvem blir kastet ut av et utested?",
    "Jeg har aldri hooka med mer enn en person i løpet av en kveld",
    "Hvem gråter seg til sex?",
    "Hvem skryter mest av antall sexpartnere de har hatt?",
    "Jeg har aldri løyet om antall sexpartnere",
    "Hvem drikker på den ene ølen hele kvelden?",
    "Pek på den som passer best inn på jakten på kjærligheten",
    "ALLE DRIKKER 4 SLURKER",
    "Jeg har aldri nakenbadet",
    "Hvem har bare misjonær?",
    "Hvem skulker skole for fest?",
    "Hvem av jentene går for yngre gutter?",
    "Jeg har aldri hatt sex på et offentlig sted",
    "Hvem trenger å drikke mer, 5 slurker",
    "Hvem av guttene går for yngre jenter?",
    "Hvem lager mest lyd i senga?",
    "Jeg har aldri blitt fersket av foreldre/familie under sex",
    "ALLE DRIKKER 5 SLURKER",
    "Pek på den som alltid prøver, men aldri får seg no",
    "Hvem røyker mest?",
    "Hvem er mest kinky i senga?",
    "Hvem får seg lettest ligg? ( ikke kjærestepar)",
    "Jeg har aldri ligget med mer enn en person i løpet av en kveld",
    "Hvem kunne tatovert en kjæreste sitt navn?",
    "Hvem bruker mest penger på det motsatte kjønn på byen?",
    "Hvem onanerer mest?",
    "Pek på den som drar på treningssenter bare for å sende bilder av at den er der",
    "ALLE DRIKKER 6 SLURKER",
    "Hvem flørter seg til gratis drikke?",
    "Jeg har aldri hatt trekant",
    "Hvem tar mest narkotiske stoffer?",
    "Hvem virker mest uskyldig, men er det ikke",
    "Hvem bruker masse penger, men har alikevel aldri penger?",
    "Jeg har aldri fantasert om noen i dette rommet",
    "Hvem bytter personlighet etter alkohol?",
    "Hvem blir hangover?",
    "Pek på den som ikke klarer å håndtere alkohol",
    "ALLE DRIKKER 7 SLURKER",
    "Hvem må jobbe hardest for ligg?",
    "Hvem kan sovne på fest/rulling?",
    "Jeg har aldri vært utro",
    "Hvem er den største skuffelsen i senga?",
    "Hvem er en ekte mamma gutt?",
    "Jeg har aldri ligget med mer enn 5 personer",
    "Hvem liker å gi oralsex?",
    "Hvem kunne gjort de sykeste tingene for penger?",
    "Pek på den som kunne onanert på et offentlig sted",
    "ALLE DRIKKER 8 SLURKER",
    "Jeg har aldri onanert til en av foreldrene til en venn",
    "Hvem er den høyeste på festen? Alle må drikke 1 slurk for hver 5 cm de er lavere",
    "Hvem kommer raskest?",
    "Hvem ser mest på porno?",
    "Jeg har aldri putta/fått den i 2’ern ved et uhell",
    "Hvem har et barn de ikke vet om?",
    "Hvem kan alle russesanger?",
    "Jeg har aldri tatt kongla",
    "Hvem skal drikke opp drikken sin?",
    "ALLE DRIKKER 9 SLURKER",
    "Jeg har aldri hatt sex mens noen andre var i rommet",
    "Hvem er dårligst på å bruke prevensjon?",
    "Hvem tar seg mest på puppene?",
    "Jeg har aldri brukt et sexleketøy",
    "Hvem drikker seg full hjemme alene?",
    "Tommel opp/ned, Topp eller bunn?",
    "Hvem drikker bare andres drikke?",
    "Jeg har aldri rulla med en russebuss",
    "Hvem blir full etter en cider?",
    "ALLE DRIKKER 10 SLURKER",
    "Hvem snuser bare andres snus?",
    "Jeg har aldri kalt noen daddy i en seksuel sammenheng?",
    "Hvem kunne havna på glattcella?",
    "Hvem kunne ditcha vennen/vennegjengen sin for et ligg på fest/byen?",
    "Hvem dropper ut av studiene?",
    "Jeg har aldri tatt dommen til noen",
    "Alle drikker antall slurker som sexpartnere de har hatt",
    "Hvem er mest høy på seg selv?",
    "Pek på den som har dårligst pullout game",
    "ALLE DRIKKER 11 SLURKER",
    "Hvem er den laveste? Alle må drikke 1 slurk for hver 5 cm de er høyere",
    "Hvem ser på KUWTK i hemmelighet?",
    "Jeg har aldri prøvd isbit trenden ;) #tiktok",
    "Hvem kunne kommet full på skolen?",
    "Hvem kunne drukket seg drita i familiebursdag?",
    "Hvem kommer til å studere på BI, fordi pappa betaler",
    "Jeg har aldri ligget med noen pga et veddemål",
    "Hvem har finest rumpe?",
    "Hvem skiller seg mest ut i mengden?",
    "ALLE DRIKKER 12 SLURKER",
    "Jeg har aldri send nakenbilde",
    "Hvem har tatt gullkongla?",
    "Hvem har pult i dag?",
    "Hvem bruker mest tid foran speilet?",
    "Hvem kunne gått vg3 om igjen, bare for å få enda en russetid?",
    "Jeg har aldri fått noen full for å ligge med de",
    "Hvem har best musikk smak?",
    "Alle som ikke har på bh må drikke",
    "Hvem skal du kysse av d samme kjønn?",
    "ALLE DRIKKER 13 SLURKER",
    "Hvem er den blondeste i rommet?",
    "Hvem vil du se ned på alle fire?",
    "Hvem tror du har hatt flest sexpartnere?",
    "Jeg har aldri pult noen jeg møtte på en app",
    "Hvem kunne du tatt med deg hjem i kveld?",
    "Hvem har pult på de rareste stedene?",
    "Jeg har aldri pult fult påkledd",
    "Hvem kunne vært utro",
    "ALLE DRIKKER 14 SLURKER",
    "Jeg har aldri gjort noe med en lærer",
    "Hvem er mest sannsynlig til å gjøre noen gravid?",
    "Hvem er mest sannsynlig for å bli gravid, for å sørge for at typen ikke dropper henne?",
    "Hvem gir de beste blowjobbene?",
  ],

  [
    "har vært i håndjern",
    "sender mest nudes",
    "har hatt sex med en kjendis",
    "har hooket med flest i rommet",
    "er den største fylliken",
    "vært utro",
    "blir den beste moren",
    "blir den beste faren",
    "har hatt trekant",
    "SKÅL 🍹",
    "har løyet for å få seg et ligg",
    "har onanert offentlig",
    "bruker mest på byn",
    "du ville vært på en øde øy med",
    "knuser flest hjerter",
    "mest sannsynlig ender opp i fengsel",
    "har hatt flest kjønnssykdommer",
    "har best musikksmak",
    "har hatt sex på et utsted",
    "SKÅL 🍹",
    "er mest bortskjemt",
    "hadde klart seg best på farmen",
    "lyser opp rommet",
    "runker mest",
    "du får vakrest barn med",
    "er flinkest på skolen",
    "har finest rumpe",
    "er den beste vennen",
    "har de fineste øyene",
    "SKÅL 🍹",
    "har hatt sex med flest nasjonaliteter",
    "har vært på glattcellen",
    "har tatt flest jomfrudommer",
    "spyr i kveld",
    "blir den beste kjæresten",
    "har gått lengst uten å ha sex",
    "du vil komme i buksene på",
    "er morsomst",
    "har flest våte drømmer",
    "SKÅL 🍹",
    "er med mile-high club",
    "er svigermors drøm",
    "er med på alt",
    "er minst flink å bruke prevensjon",
    "danser best",
    "er minst ansvarlig",
    "lukter best",
    "er kåtest",
    "er den beste sjekkeren",
    "SKÅL 🍹",
    "har høyest IQ",
    "har den skitneste loggen",
    "hadde blitt den beste statsministeren",
    "er mest sporty",
    "er festens midtpunkt",
    "er best å kysse",
    "er mest selvopptatt",
    "rundet netflix",
    "hadde overlevd the hunger games",
    "SKÅL 🍹",
    "blir millionær først",
    "er lærerens favoritt",
    "gråter etter sex",
    "har det mest slitte knærne",
    "er best i sengen",
    "er villest",
    "har shavet og er ",
    "har hatt flest blackouts",
    "har størst penis",
    "SKÅL 🍹",
    "er lengst i dusjen",
    "blir mest suksessfull",
    "ikke sover hjemme i natt",
    "er flinkest med barn",
    "har størst kjendisfaktor",
    "har hatt sex flest 99'ere",
    "har best sjans på deg",
    "har hatt mest tinder-sex",
    "har hatt sex med flest i klassen sin",
    "SKÅL 🍹",
    "du ville hatt som beerpong partner",
    "blir gjenkjent på kondomeriet",
    "du stoler mest på",
    "hadde gjort mest for minst penger",
    "hooker mest",
    "lager de sykeste lydene i sengen",
    "blir raskest sjalu",
    "mest sannsynlig kunne spilt i en porno",
    "mest sannsynlig hadde betalt for den",
    "SKÅL 🍹",
    "får flest bootycalls",
    "er den største stalkeren",
    "kommer raskest",
    "har sex på første date",
    "er mest overlegen",
    "blir spandert mest på på byn",
    "er mest klar for arbeidslivet",
    "tømmer og rømmer",
    "skal ta bånnski med deg",
    "SKÅL 🍹",
  ],
];

const options = ["Carmen's", "Let's get fucked", "Something"];

export default function Hundred({
  navigation,
  route,
}: NavigationProps<"Point">) {
  const [chosenOption, setChosenMode] = useState(0);
  const [chosenPack, setChosenPack] = useState(hundredPack[0]);

  useEffect(() => {
    setChosenPack(hundredPack[chosenOption]);
  }, [chosenOption]);

  return (
    <Container>
      {/* Options */}
      <View style={tw("w-full flex items-center")}>
        <View
          style={tw("flex flex-row justify-between bg-base-3 p-0.5 rounded-md")}
        >
          {options.map((option, key) => (
            <TouchableOpacity key={key} onPress={() => setChosenMode(key)}>
              <View
                style={tw(
                  `${
                    chosenOption === key ? "bg-base" : ""
                  } p-2 rounded-md flex items-center`
                )}
              >
                <Text style={tw("text-theme text-xs")}>{option}</Text>
              </View>
            </TouchableOpacity>
          ))}
        </View>
      </View>
      <ScrollView style={tw("mx-6")}>
        {chosenPack.map((item, key) => {
          return (
            <View key={key} style={tw("mb-6")}>
              <Text style={tw("text-theme text-lg")}>{key + 1}:</Text>
              <Text style={tw("text-theme text-lg")}>{item}</Text>
            </View>
          );
        })}
      </ScrollView>
    </Container>
  );
}
